# Generated by Django 4.1.4 on 2023-01-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/images/'),
        ),
    ]
