# Generated by Django 4.1.4 on 2023-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_submissions_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
