# Generated by Django 4.1.4 on 2023-02-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_events_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissions',
            options={'ordering': ['created']},
        ),
    ]
