# Generated by Django 4.1.4 on 2023-01-28 16:55

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('JournalId', models.CharField(max_length=200, unique=True)),
                ('journalName', models.CharField(max_length=200)),
                ('journalDoi', models.CharField(max_length=200)),
                ('journalArticle', models.FileField(upload_to='files/', validators=[users.models.validate_pdf])),
                ('ugcListed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('journalNationality', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conferenceId', models.CharField(max_length=200, unique=True)),
                ('conferenceName', models.CharField(max_length=200)),
                ('conferenceDoi', models.CharField(max_length=200)),
                ('conferenceArticle', models.FileField(upload_to='files/', validators=[users.models.validate_pdf])),
                ('ugcListed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('conferenceNationality', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
    ]
