# Generated by Django 4.1.4 on 2023-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='FacultyPhone',
            field=models.CharField(max_length=10),
        ),
    ]
